### ISSUE TITLE
Please create a new Google Map API key

### ISSUE THREAD

**Issue by ajithranka** [laurenwong1207/Week-03#1]
Hi @laurenwong1207,

I got an email this morning from Google Cloud informing me that your project links to my Google Map API key. You likely referred to my p5.js [sketch](https://editor.p5js.org/ajithranka/sketches/q5YgMPAvD) while working on your project.

<img width="612" alt="google-email" src="https://github.com/laurenwong1207/Week-03/assets/11095038/46879ba9-462c-4500-bd7e-92e2f33b5502">

Usually this isn't trouble, but since these API keys are used to track and bill usage, I plan to delete the key. Your map won't load anymore after the key has been deleted.

Please follow [these steps](https://developers.google.com/maps/documentation/javascript/get-api-key) to create your own key and replace it in the script.

https://github.com/laurenwong1207/Week-03/blob/main/Weather%20API%20website/index.html#L9

**Comment by laurenwong1207** [comment]
Hi Ajith,



Thank you for bringing this to my attention, and I apologize for any
inconvenience caused. I've already taken the necessary steps to address
this issue.



I've updated the Google Map API key in my project to my own, ensuring that
there won't be any disruption in the functionality of the map once your key
is deleted.



If you have any further questions or concerns, please feel free to reach
out.



Best regards,

Jinlan
